# Generated by Django 4.2.7 on 2023-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0005_alter_store_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshour',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storetimezone',
            name='store',
        ),
        migrations.AddField(
            model_name='businesshour',
            name='store_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storetimezone',
            name='store_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
