# Generated by Django 4.2.7 on 2023-11-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_monitor', '0006_remove_businesshour_store_remove_storetimezone_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetimezone',
            name='timezone_str',
            field=models.CharField(default='America/Chicago', max_length=100),
        ),
    ]
